### ISSUE TITLE
calibrate.lm should use data = object$model, not data = eval(object$call$data)

### ISSUE THREAD

**Issue by amackey** [bgreenwell/investr#18]
In cases when calibrate() is used with multiple lm model objects, calibrate.lm() currently re-evaluates the lm model's call info, which may have changed since the call to lm() occurred.  Thus, instead of `data = eval(object$call$data)`, you certainly want `data = object$model`

**Comment by bgreenwell** [comment]
Honestly, the "lm" method of calibrate should be re-written and probably not call the "formula" method at all. The "formula" method, which calls the default method, uses lm (or soon lm.fit) to fit a linear model -- but this seems wasteful. I'll try and work on it throughout the week. Thanks for reporting the issue!

**Comment by bgreenwell** [comment]
Should be fixed now.
